version: '3'
services:
  redis-server:
    image: 'redis'
    restart: on-failure
  node-app:
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - /app/node_modules
      - .:/app
