version: '3'
services:
  redis-server:
    image: 'redis'
    restart: on-failure
  node-app:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: on-failure
