version: '3'
services:
  redis-server:
    image: 'redis'
    restart: on-failure
  node-app:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    restart: on-failure
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - /app/node_modules
      - .:/usr/app
    command: npm run dev
