version: '3'
services:
  postgres-server:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 4000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev
      PGADMIN_DEFAULT_PASSWORD: dev
  redis-server:
    image: 'redis'
    restart: on-failure
  node-app:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    restart: on-failure
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_HOST: redis-server
      DB_USER: dev
      DB_PASSWORD: dev
      DB_HOST: postgres-server
    volumes:
      - /app/node_modules
      - .:/usr/app
    command: npm run dev
